---

openapi: '3.0.0'
info:
  title: eCloud Admin API
  version: '1.0.0'

servers:
  - url: https://api.ukfast.io

security:
  - api_key:
      - api_key

paths:

components:
  securitySchemes:
    api_key:
      type: apiKey
      description: API key authentication
      in: header
      name: Authorization

  schemas:
